theme: jekyll-theme-cayman

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Katy Felkner"
keywords:    "computer science, python, computer programmer, digital humanities, classics, digital classics"
description: "computer science undergrad and aspiring digital humanist"
source_link: ""
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)

kramdown:
  auto_ids:  false
